import {google} from 'googleapis';

export default defineEventHandler(async (event) => {
  let reqCookie = getCookie(event, 'authPayload')!
  let req = JSON.parse(reqCookie)
  if(!req){
    console.error('what')
  }
  console.log(req)
  deleteCookie(event, 'authPayload') //KILL!!!!
  //debugging generated by claude, stumped on fixing authentication issue.
  const existingTokens = getCookie(event, 'google_tokens');
  if(req.signUp || req.signIn){
    setCookie(event, 'signupSpecifications', JSON.stringify(req), {
      sameSite: 'none',
      secure: true,  
      path: '/',  
      httpOnly: false,  
      maxAge: 60 * 5 
    })
  } else {
    console.error('invalid route!!!')
    return
  }
  if (existingTokens) {
    try {
      const parsedTokens = JSON.parse(existingTokens);
      const revokeUrl = `https://oauth2.googleapis.com/revoke?token=${parsedTokens.access_token}`;
      await fetch(revokeUrl, { method: 'POST' });
    } catch (error) {
      console.log('Error revoking token:', error);
    }
  }
  const oauthClient = new google.auth.OAuth2(process.env.OAUTHID, process.env.OAUTHSECRET, process.env.REDIRECT)
  const url = oauthClient.generateAuthUrl({
    prompt: 'consent',
    access_type:'offline',
    include_granted_scopes: false,
    scope:[ 'https://www.googleapis.com/auth/calendar',
      'https://www.googleapis.com/auth/contacts.readonly',
     ],
  })
  console.log("Login URL", url)
  sendRedirect(event, url)
})
