export const industryDropdownChoices = [
  { value: "Accommodation", text: "Accommodation" },
  { value: "Accommodation and Food Services", text: "Accommodation and Food Services" },
  { value: "Administrative and Support Services", text: "Administrative and Support Services" },
  { value: "Administrative and Support and Waste Management and Remediation Services", text: "Administrative and Support and Waste Management and Remediation Services" },
  { value: "Agriculture, Forestry, Fishing and Hunting", text: "Agriculture, Forestry, Fishing and Hunting" },
  { value: "Air Transportation", text: "Air Transportation" },
  { value: "Ambulatory Health Care Services", text: "Ambulatory Health Care Services" },
  { value: "Amusement, Gambling, and Recreation Industries", text: "Amusement, Gambling, and Recreation Industries" },
  { value: "Animal Production", text: "Animal Production" },
  { value: "Apparel Manufacturing", text: "Apparel Manufacturing" },
  { value: "Arts, Entertainment, and Recreation", text: "Arts, Entertainment, and Recreation" },
  { value: "Beverage and Tobacco Product Manufacturing", text: "Beverage and Tobacco Product Manufacturing" },
  { value: "Broadcasting (except Internet)", text: "Broadcasting (except Internet)" },
  { value: "Building Material and Garden Equipment and Supplies Dealers", text: "Building Material and Garden Equipment and Supplies Dealers" },
  { value: "Chemical Manufacturing", text: "Chemical Manufacturing" },
  { value: "Clothing and Clothing Accessories Stores", text: "Clothing and Clothing Accessories Stores" },
  { value: "Computer and Electronic Product Manufacturing", text: "Computer and Electronic Product Manufacturing" },
  { value: "Construction", text: "Construction" },
  { value: "Construction of Buildings", text: "Construction of Buildings" },
  { value: "Couriers and Messengers", text: "Couriers and Messengers" },
  { value: "Credit Intermediation and Related Activities", text: "Credit Intermediation and Related Activities" },
  { value: "Crop Production", text: "Crop Production" },
  { value: "Data Processing, Hosting, and Related Services", text: "Data Processing, Hosting, and Related Services" },
  { value: "Education and Health Services", text: "Education and Health Services" },
  { value: "Educational Services", text: "Educational Services" },
  { value: "Electrical Equipment, Appliance, and Component Manufacturing", text: "Electrical Equipment, Appliance, and Component Manufacturing" },
  { value: "Electronics and Appliance Stores", text: "Electronics and Appliance Stores" },
  { value: "Fabricated Metal Product Manufacturing", text: "Fabricated Metal Product Manufacturing" },
  { value: "Finance and Insurance", text: "Finance and Insurance" },
  { value: "Financial Activities", text: "Financial Activities" },
  { value: "Fishing, Hunting and Trapping", text: "Fishing, Hunting and Trapping" },
  { value: "Food Manufacturing", text: "Food Manufacturing" },
  { value: "Food Services and Drinking Places", text: "Food Services and Drinking Places" },
  { value: "Food and Beverage Stores", text: "Food and Beverage Stores" },
  { value: "Forestry and Logging", text: "Forestry and Logging" },
  { value: "Funds, Trusts, and Other Financial Vehicles", text: "Funds, Trusts, and Other Financial Vehicles" },
  { value: "Furniture and Home Furnishings Stores", text: "Furniture and Home Furnishings Stores" },
  { value: "Furniture and Related Product Manufacturing", text: "Furniture and Related Product Manufacturing" },
  { value: "Gasoline Stations", text: "Gasoline Stations" },
  { value: "General Merchandise Stores", text: "General Merchandise Stores" },
  { value: "Goods-Producing Industries", text: "Goods-Producing Industries" },
  { value: "Health Care and Social Assistance", text: "Health Care and Social Assistance" },
  { value: "Health and Personal Care Stores", text: "Health and Personal Care Stores" },
  { value: "Heavy and Civil Engineering Construction", text: "Heavy and Civil Engineering Construction" },
  { value: "Hospitals", text: "Hospitals" },
  { value: "Information", text: "Information" },
  { value: "Insurance Carriers and Related Activities", text: "Insurance Carriers and Related Activities" },
  { value: "Internet Publishing and Broadcasting", text: "Internet Publishing and Broadcasting" },
  { value: "Leather and Allied Product Manufacturing", text: "Leather and Allied Product Manufacturing" },
  { value: "Leisure and Hospitality", text: "Leisure and Hospitality" },
  { value: "Lessors of Nonfinancial Intangible Assets (except Copyrighted Works)", text: "Lessors of Nonfinancial Intangible Assets (except Copyrighted Works)" },
  { value: "Machinery Manufacturing", text: "Machinery Manufacturing" },
  { value: "Management of Companies and Enterprises", text: "Management of Companies and Enterprises" },
  { value: "Manufacturing", text: "Manufacturing" },
  { value: "Merchant Wholesalers, Durable Goods", text: "Merchant Wholesalers, Durable Goods" },
  { value: "Merchant Wholesalers, Nondurable Goods", text: "Merchant Wholesalers, Nondurable Goods" },
  { value: "Mining (except Oil and Gas)", text: "Mining (except Oil and Gas)" },
  { value: "Mining, Quarrying, and Oil and Gas Extraction", text: "Mining, Quarrying, and Oil and Gas Extraction" },
  { value: "Miscellaneous Manufacturing", text: "Miscellaneous Manufacturing" },
  { value: "Miscellaneous Store Retailers", text: "Miscellaneous Store Retailers" },
  { value: "Monetary Authorities - Central Bank", text: "Monetary Authorities - Central Bank" },
  { value: "Motion Picture and Sound Recording Industries", text: "Motion Picture and Sound Recording Industries" },
  { value: "Motor Vehicle and Parts Dealers", text: "Motor Vehicle and Parts Dealers" },
  { value: "Museums, Historical Sites, and Similar Institutions", text: "Museums, Historical Sites, and Similar Institutions" },
  { value: "Natural Resources and Mining", text: "Natural Resources and Mining" },
  { value: "Nonmetallic Mineral Product Manufacturing", text: "Nonmetallic Mineral Product Manufacturing" },
  { value: "Nonstore Retailers", text: "Nonstore Retailers" },
  { value: "Nursing and Residential Care Facilities", text: "Nursing and Residential Care Facilities" },
  { value: "Oil and Gas Extraction", text: "Oil and Gas Extraction" },
  { value: "Other Information Services", text: "Other Information Services" },
  { value: "Other Services (except Public Administration)", text: "Other Services (except Public Administration)" },
  { value: "Paper Manufacturing", text: "Paper Manufacturing" },
  { value: "Performing Arts, Spectator Sports, and Related Industries", text: "Performing Arts, Spectator Sports, and Related Industries" },
  { value: "Personal and Laundry Services", text: "Personal and Laundry Services" },
  { value: "Petroleum and Coal Products Manufacturing", text: "Petroleum and Coal Products Manufacturing" },
  { value: "Pipeline Transportation", text: "Pipeline Transportation" },
  { value: "Plastics and Rubber Products Manufacturing", text: "Plastics and Rubber Products Manufacturing" },
  { value: "Postal Service", text: "Postal Service" },
  { value: "Primary Metal Manufacturing", text: "Primary Metal Manufacturing" },
  { value: "Printing and Related Support Activities", text: "Printing and Related Support Activities" },
  { value: "Private Households", text: "Private Households" },
  { value: "Professional and Business Services", text: "Professional and Business Services" },
  { value: "Professional, Scientific, and Technical Services", text: "Professional, Scientific, and Technical Services" },
  { value: "Publishing Industries (except Internet)", text: "Publishing Industries (except Internet)" },
  { value: "Rail Transportation", text: "Rail Transportation" },
  { value: "Real Estate", text: "Real Estate" },
  { value: "Real Estate and Rental and Leasing", text: "Real Estate and Rental and Leasing" },
  { value: "Religious, Grantmaking, Civic, Professional, and Similar Organizations", text: "Religious, Grantmaking, Civic, Professional, and Similar Organizations" },
  { value: "Rental and Leasing Services", text: "Rental and Leasing Services" },
  { value: "Repair and Maintenance", text: "Repair and Maintenance" },
  { value: "Retail Trade", text: "Retail Trade" },
  { value: "Scenic and Sightseeing Transportation", text: "Scenic and Sightseeing Transportation" },
  { value: "Securities, Commodity Contracts, and Other Financial Investments and Related Activities", text: "Securities, Commodity Contracts, and Other Financial Investments and Related Activities" },
  { value: "Service-Providing Industries", text: "Service-Providing Industries" },
  { value: "Social Assistance", text: "Social Assistance" },
  { value: "Specialty Trade Contractors", text: "Specialty Trade Contractors" },
  { value: "Sporting Goods, Hobby, Book, and Music Stores", text: "Sporting Goods, Hobby, Book, and Music Stores" },
  { value: "Support Activities for Agriculture and Forestry", text: "Support Activities for Agriculture and Forestry" },
  { value: "Support Activities for Mining", text: "Support Activities for Mining" },
  { value: "Support Activities for Transportation", text: "Support Activities for Transportation" },
  { value: "Telecommunications", text: "Telecommunications" },
  { value: "Textile Mills", text: "Textile Mills" },
  { value: "Textile Product Mills", text: "Textile Product Mills" },
  { value: "Trade, Transportation, and Utilities", text: "Trade, Transportation, and Utilities" },
  { value: "Transit and Ground Passenger Transportation", text: "Transit and Ground Passenger Transportation" },
  { value: "Transportation Equipment Manufacturing", text: "Transportation Equipment Manufacturing" },
  { value: "Transportation and Warehousing", text: "Transportation and Warehousing" },
  { value: "Truck Transportation", text: "Truck Transportation" },
  { value: "Utilities", text: "Utilities" },
  { value: "Warehousing and Storage", text: "Warehousing and Storage" },
  { value: "Waste Management and Remediation Services", text: "Waste Management and Remediation Services" },
  { value: "Water Transportation", text: "Water Transportation" },
  { value: "Wholesale Electronic Markets and Agents and Brokers", text: "Wholesale Electronic Markets and Agents and Brokers" },
  { value: "Wholesale Trade", text: "Wholesale Trade" },
  { value: "Wood Product Manufacturing", text: "Wood Product Manufacturing" }
];
